moka-guys/automate_demultiplex

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/265)
=> updated mokawes1.7 config

automate_demultiplex_config.py
updated pipeline ID to 3639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/266)
=> updated mokawes pipeline ID

DNANexus_upload_agent.py, automate_demultiplex_config.py
Changed Mokawes stages in the config file.
Pipeline ID also changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/267)
=> Mokawesv1.7 update

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/269)
=> update to smartsheet app where api key is not packaged

upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/273)
=> Remove depends on statement for ntccon

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/274)
=> add padding for HC STG panels and make sapientia upload manual

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/295)
=> v33 into production

upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/299)
=> add sleep command before IVA dx run cmd

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/300)
=> add panelid to audit trail

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/301)
=> add email to m.neat

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/303)
=> fix incorrect mokaonc email

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/304)
=> v35 into production

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/307)
=> congenica pan numbers into production

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/327)
=> master to production v38.0

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/332)
=> correct version of multiqc app

automate_demultiplex_config.py, decision_support_tool_inputs.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/333)
=> v39 into production

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/336)
=> v39.1 into production

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/339)
=> Updated to use upload_multiqc_v1.4.0

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/340)
=> v39.2 into Production

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)
=> V40.0.0 attempt2

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/350)
=> v40.0.0 into production

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/351)
=> correct name of config.samplesheets to config.samplesheets_dir

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/361)
=> v42.0.0 into prod

automate_demultiplex_config.py, demultiplex.py, samplesheet_verifier.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)
=> try to fix tso500 tarball creation

automate_demultiplex_config.py, decision_support_tool_inputs.py, demultiplex.py, samplesheet_verifier.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/370)
=> v43.0.1 into prod

upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/371)
=> fixes issue with novaseq tso500 argument

automate_demultiplex_config.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/376)
=> Smartsheet update

demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/379)
=> disable smartsheet command

automate_demultiplex_config.py, demultiplex.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/380)
=> Disable SmartSheet run command

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/402)
=> update TSO500 apps and BED file

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/404)
=> v44.2.0 merge to production

samplesheet_verifier.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/413)
=> add LRPCR as library prep option

automate_demultiplex_config.py, samplesheet_verifier.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/418)
=> v43.3.1 into prod

.github/workflows/on-pull-request.yaml, upload_and_setoff_workflows.py
Added GitHub Actions config to check for syntax errors. This should allow to add branch protection to master & Production from merging non-functional code.
(formatting/style errors are not active)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/419)
=> corrected syntax error, added flake8 check

.github/workflows/on-pull-request.yaml, automate_demultiplex_config.py, decision_support_tool_inputs.py, samplesheet_verifier.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/421)
=> v43.3.3 into prod

automate_demultiplex_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/427)
=> add support for mike mitchels' pan numbers

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464)
=> Feature/mokapipe v2.17

automate_demultiplex_config.py, upload_and_setoff_workflows.py
Update mokapipe pipeline ID and version, and polyedge inputs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/476)
=> Feature/mokapipe v2.18

automate_demultiplex_config.py, upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/477)
=> Dry lab pan numbers and TSO and multiqc app updates

upload_and_setoff_workflows.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/513)
=> add new line to congenica run commands file. Close #512

config/ad_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/542)
=> Fix test mode setup when on master branch

config/ad_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/573)
=> Aviti integrity check not needed

setoff_workflows/build_dx_commands.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/575)
=> fix congenica bam string

demultiplex/test_demultiplex.py, requirements.txt
Further changes to pytest scripts and updated requirements.txt file to samplesheet_validator v1.4 with updated changes needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/587)
=> Av demultiplex

config/panel_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/590)
=> Changed Congenica project id number for R414 for St Georges

config/ad_config.py, setoff_workflows/setoff_workflows.py
This is to update archer api upload docker for workstation dev branch. "WS_dev_branch_from_v45.4.0" is branched from earlier release for Workstation AS (ie. v45.4.0). 
New docker was tested using ADX25026 and confirmed passed. Error message on sw log file was also tested and confirmed to show ERROR if api upload fails (Rapid7 needs to capture this error though)
NOTE: Once the new docker is deployed on the Workstation, the credential key file has to be updated on the workstation as well since the new docker use the new key.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/596)
=> update adx docker for workstation

config/ad_config.py, setoff_workflows/setoff_workflows.py
This is to merge WS_dev_branch_from_v45.4.0 to ws_main_from_v45.4.0. 
This is to replace the existing Archer upload docker (in bash) with a new docker (in python) with re-try function for network connection issue.  In addition, a bugfix was done to capture the error if the archer upload fails for any reason.  
Note: since AS main branch in github repo is for Turing workstation, a new dev branch was created from v45.4.0 that is the most updated workstation AS version. The changes were done on a feature branch and merged into ws_dev branch and then merged to ws_main branch that was also branched from v45.4.0. 
Prod mode branch for ws is also updated so that both "main" and "ws_main_from_v45.4.0" are used as prod mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Ws dev branch from v45.4.0

.github/workflows/on-pull-request.yaml, config/ad_config.py
This is to merge ws_dev branch to ws_main branch. Update was done on yml file to trigger github action on PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/600)
=> Ws dev branch from v45.4.0 for PR action

.github/workflows/on-pull-request.yaml, config/ad_config.py
This is to revert the workstation prod from `ws_main_from_45.4.0` to its original correct version 45.4.1.
- a dev branch named `ws_dev_branch_from_v45.4.1` was created based on 45.4.1.
- a feature branch named `reverting_branch`  was created based on `ws_dev_branch_from_v45.4.1`
- On the feature branch, changes were done to include prod branch name in config and yml file .
- after these changes have been code reviewed and merged into `ws_dev_branch_from_v45.4.1`, the dev branch is going to merged into `ws_main_branch_from_v45.4.1` that also bases on version 45.4.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/602)
=> update to revert to 45.4.1

.github/workflows/on-pull-request.yaml, config/ad_config.py
This is to merge ws_dev_branch_from_v45.4.1 to ws_main_branch_from_v45.4.1. This is to revert back the workstation AS to previous correct version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/603)
=> Ws dev branch from v45.4.1

upload_runfolder/upload_runfolder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/611)
=> Amended pattern used to count local files to compare to uploaded files

config/ad_config.py, upload_runfolder/upload_runfolder.py
Changes as per [PR613](https://github.com/moka-guys/automate_demultiplex/pull/613)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/automate_demultiplex/614)
=> Addition of sleep delay to Congenica commands
